name: dictionary_english_word
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'







dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  json_annotation: ^4.5.0
  build_runner: ^2.1.11
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter_tts: ^3.0.0
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  shared_preferences: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7  
  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
